package dev.afcasco.fctsorterbackend.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;

@Entity
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
public class Company {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(name = "Company ID",description = "Autogenerated value", example = "1")
    private Long id;
    @Schema(name = "CIF",description = "Company identification document", example = "B5555555")
    private String cif;
    @Schema(name = "Name",description = "Company name",example = "Compu-Global-Hyper-Mega-Net")
    private String name;
    @Schema(name = "Address",description = "Includes street, number and/or building name...", example = "742 Evergreen Terrace")
    private String address;
    @Schema(name = "City", description = "City name", example = "Springfield")
    private String city;
    @Schema(name = "Zip Code",description = "Zip code number",example = "80085")
    private String zipCode;
    @Schema(name = "Phone number", description = "Mobile/office telephone number", example = "555-6528")
    private String phone;
    @Schema(name = "Verified status", description = "Current registered status", example = "ACTIVE")
    @Enumerated(EnumType.STRING)
    private Status status;


}
