version: '3'

services:

  fct-finder:
    container_name: fct-finder
    image: afcasco/fct-finder
    ports:
      - "8080:8080"
    environment:
      #spring.profiles.active: local
      server.port: 8080
      spring.datasource.url: jdbc:mysql://fct-finder-db:3306/fct_finder
      spring.datasource.username: fctfinder
      spring.datasource.password: fctfinder
      fctfinder.app.jwtSecret: ==================================fct-finder-secret=================================
    networks:
      - fct-finder-net
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: fct-finder-db
    image: mysql:latest
    ports:
      - "3500:3306"
    environment:
      MYSQL_DATABASE: fct_finder
      MYSQL_USER: fctfinder
      MYSQL_PASSWORD: fctfinder
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    networks:
      - fct-finder-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  fct-finder-net:
    name: fct-finder
