FROM maven:3-openjdk-17-slim AS MAVEN_TOOL_CHAIN
COPY ../pom.xml /tmp/
COPY ../src /tmp/src/
WORKDIR /tmp/
RUN mvn package

FROM eclipse-temurin:17-jre-alpine
COPY --from=MAVEN_TOOL_CHAIN /tmp/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar app.jar"]