# Builds docker image from the current code.
version: '3'
services:
  fct-finder:
    container_name: fct-finder
    build: ../
    ports:
      - "8080:8080"
    # Override spring application-prod.properties with desired values
    environment:
      # mysql url (databse needs to exist but can be empty)
      spring.datasource.url: jdbc:mysql://172.24.0.2:3306/fct_finder
      # mysql user
      spring.datasource.username: fctfinder
      # mysql password
      spring.datasource.password: fctfinder
      #
      fctfinder.app.jwtSecret: =================================fctFinderSecretKey=spring=afcasco=================================