# Runs application container
# Edit database url/details to match your running database
version: '3'
services:
  fct-finder:
    container_name: fct-finder
    image: test:latest
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://192.168.1.88:53306/fct_finder
      spring.datasource.username: fctfinder
      spring.datasource.password: fctfinder
      fctfinder.app.jwtSecret: ==================================fctFinderSecretKey=spring=afcasco=================================