# Build docker image and runs it as a stack with a new mysql container.
version: '3.8'

services:

  fct-finder:
    container_name: fct-finder
    build: ../.
    ports:
      - "8080:8080"
    environment:
      #server.port: 8080
      spring.datasource.url: jdbc:mysql://fct-finder-db:3306/fct_finder
      spring.datasource.username: fctfinder
      spring.datasource.password: fctfinder
      fctfinder.app.jwtSecret: ==================================fctFinderSecretKey=spring=afcasco=================================
    networks:
      - fct-finder-net
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: fct-finder-db
    image: mysql:latest
    ports:
      - "3500:3306"
    environment:
      MYSQL_DATABASE: fct_finder
      MYSQL_USER: fctfinder
      MYSQL_PASSWORD: fctfinder
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    networks:
      - fct-finder-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 20

networks:
  fct-finder-net:
    name: fct-finder
